### ISSUE TITLE
feat: Capusle Skin API 셋팅

### ISSUE THREAD

**Issue by comst19** [tukcomCD2024/DroidBlossom#146]
## 어떤 기능인가요?

> Capsule Skin에 관련된 API 셋팅

## 작업 상세 내용

- [x] 캡슐 스킨 목록 조회 API
- [x] 캡슐 스킨 생성 API

**Comment by hangunhee39** [comment]
스킨 목록 조회 - 캡슐 생성에 적용 완

**Comment by comst19** [comment]
캡슐 스킨 생성 성공 - 모션 추가 필요
