### ISSUE TITLE
refact: 이미지, 동영상 uri/url 한 번에 받기

### ISSUE THREAD

**Issue by comst19** [tukcomCD2024/DroidBlossom#191]
## 어떤 기능인가요?

> 갤러리에서 이미지, 동영상을 한 번에 받고 구분
> 캡슐 디테일에서 이미지, 동영상 한번에 받고 구분

## 작업 상세 내용

- [x] 갤러리에서 이미지, 동영상 둘 다 선택할 수 있게 하기
- [x] 선택된 uri를 이미지, 동영상으로 구분하여 파일로 만들기
- [x] 캡슐 디테일에서 이미지 , 동영상 한 리사이클뷰에 보기
- [x] 캡슐 디테일에서 이미지, 동영상 클릭시 구분에서 image/video activity 로 이동

**Comment by comst19** [comment]
확인 후 기존 코드를 변경해야함

**Comment by hangunhee39** [comment]
캡슐 디테일 완료
