### ISSUE TITLE
fix: 각 화면에 api로 받은 데이터 중복 문제

### ISSUE THREAD

**Issue by comst19** [tukcomCD2024/DroidBlossom#390]
## 어떤 버그인가요?

> 각 화면에 api로 받은 데이터가 중복되어 화면에 그려지는 버그

## 작업 상세 내용

- [x] 마이페이지 캡슐 리스트
- [x] 소셜 - public, group 리스트 
- [x] 스킨 - 스킨 리스트
- [x] 캡슐 생성에서 스킨
- [x] 친구 리스트
- [x] 그룹 리스트
- [x] 친구 요청 받은 리스트
- [x] 그룹 요청 받은 리스트
- [x] 알림 리스트

**Comment by hangunhee39** [comment]
리스트 empty 예외처리

**Comment by comst19** [comment]
코루틴 작업 관리 + Throttling(first)
